# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publishing Restaurent app

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment" 
        required: true
        type: choice 
        default: dev
        options:
          - dev
          - uat
          - stg
          - uatprod
          - stgprd 
          - prd
          - uatokd 
          - citokd 
          - devokd 

  push: 
    branches: 
      - main

env:
  IMAGE_NAME: restaurent-app
  IMAGE_TAG: Delivery001
  NAMESPACE: deployment-images

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ env.IMAGE_TAG }}
      
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm 

      - name: Verify Version
        run: | 
          node --version
          npm --version

      - name: Install Dependencies 
        run: | 
          npm install --no-audit --no-fund 

      - name: Build Angular Application
        run: | 
          pwd 
          ls -l 
          ls -l node_modules/.bin
          ls -l node_modules/bin
          ls -l node_modules/bin/ng
          ls -l node_modules/.bin
          ls -l node_modules/bin/
          ls -l node_modules/bin/ng 
          ls -la ./node_modules/.bin/ng
          ls -la ./node_modules/ng
          ls -la node_modules/
          npm run build -- --configuration production
  
